!!python/object:__main__.Configuration
repositoryUrl: 'https://github.com/apache/mahout'
repositoryShortname: 'mahout'
repositoryPath: '/Users/manikhossain/Downloads/GitProject/DevNetworkPython/repo/mahout'
analysisOutputPath: '/Users/manikhossain/Downloads/GitProject/DevNetworkPython/apachemahoutmahout'
aliasPath: '/Users/manikhossain/Downloads/GitProject/DevNetworkPython/mahout.yml'
aliasSimilarityMaxDistance: 0.25

